refactor: use images from AWS Private ECR instead of public registries
juspay/hyperswitch-cdk pull request #130
Opened 2024-04-26 12:58 UTC by prasunna09

2024-04-26 13:06 UTC, jagan-jaya requested changes

2024-04-26 13:06 UTC, jagan-jaya commented on dependencies/code_builder/buildspec.yml
> +              aws ecr create-repository --repository-name "$REPO_NAME" --image-scanning-configuration scanOnPush=true
will it ignore if the repo already present?

2024-04-26 13:06 UTC, jagan-jaya commented on install.sh
> +    echo `cdk deploy --require-approval never -c db_pass=$DB_PASS -c admin_api_key=$ADMIN_API_KEY -c aws_arn=$AWS_ARN -c master_enc_key=$MASTER_ENC_KEY -c vpn_ips=$VPN_IPS -c base_ami=$base_ami -c en
this script might get executed, is it needed?

2024-04-26 13:06 UTC, jagan-jaya commented on lib/aws/eks.ts
> +              image: `${privateEcrRepository}/juspaydotin/hyperswitch-control-center:v1.29.9`
is this version tested in local?

2024-04-26 13:06 UTC, jagan-jaya commented on lib/aws/eks.ts
> +                kms_jwekey_vault_encryption_key: locker?.locker_ec2.locker_pair.public_key || kmsSecrets.kms_jwekey_vault_encryption_key,
undo this change

2024-04-26 13:06 UTC, jagan-jaya commented on lib/aws/eks.ts
> +                kms_jwekey_vault_private_key: locker?.locker_ec2.tenant.private_key || kmsSecrets.kms_jwekey_vault_private_key,
undo this change

2024-04-26 13:06 UTC, jagan-jaya commented on values.yaml
this file not supposed to be in CDK. please remove it immediately from main repo if present

2024-04-26 13:18 UTC, jagan-jaya approved these changes

2024-04-26 13:28 UTC, nitesh-balla requested changes

2024-04-26 13:28 UTC, nitesh-balla commented on dependencies/code_builder/buildspec.yml
>          done
Why are we doing this?

2024-04-26 13:28 UTC, nitesh-balla commented on lib/aws/userdata.sh
Please revert these changes back for now.

2024-04-26 13:28 UTC, nitesh-balla commented on dependencies/code_builder/buildspec.yml
> +        }
We have tag immutability disabled for the repositories that are created, So, we can upload the same tag multiple times into the repository without any error! Deletion isn't required.

2024-04-30 10:45 UTC, nitesh-balla approved these changes

2024-05-02 10:00 UTC, nitesh-balla approved these changes

2024-05-02 10:00 UTC, merged