feat(card-vault): add code to integrate card vault on cdk
juspay/hyperswitch-cdk pull request #32
Opened 2023-11-21 12:19 UTC by NishantJoshi00

## Description

Add card vault support for CDK

2023-11-22 09:19 UTC, jagan-jaya requested changes

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/components.ts
> +    let secret = new Secret(scope, "locker-db-master-user-secret", {
will this secret throw error for `secret already present` when we run it second time? 
If it does then pls fix it to work with mulitple updates

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/components.ts
> +    let schemaBucket = new s3.Bucket(scope, "LockerSchemaBucket", {
can you use existing bucket created in rds.ts file? so that we can have all the cdk related items in one bucket

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/components.ts
> +        publiclyAccessible: true,
remove this

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/encryption.py
> +    lambda data: kms_client.encrypt(keyId=key_id, Plaintext=data)
add a `return`

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/components.ts
> +    const initializeDBFunction = new Function(scope, "InitializeDBFunction", {
change name `InitializeDBFunction `

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/components.ts
> +    new cdk.triggers.Trigger(scope, "InitializeDBTrigger", {
change name `InitializeDBTrigger `

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/migration.py
> +def lambda_handler(event, context):
remove this lamda handler and change the existing `lamda_handler` in rds.ts

2023-11-22 09:19 UTC, jagan-jaya commented on lib/aws/card-vault/user-data.sh
remove this file

2023-11-22 09:29 UTC, NishantJoshi00 commented on lib/aws/card-vault/LockerSetup.ts
No! removing this now

2023-11-27 12:09 UTC, jagan-jaya approved these changes

2023-11-29 15:43 UTC, closed without merging