chore: kms encryption for admin api key
juspay/hyperswitch-cdk pull request #50
Opened 2023-12-19 10:38 UTC by dracarys18

2023-12-20 06:16 UTC, nitesh-balla commented on install.sh
> +
Let us update one click deployment files `production.yml` and `single-click.sh` files for the same.

2023-12-20 06:16 UTC, nitesh-balla commented on install.sh
> +  read -s MASTER_KEY
Where are we using this `MASTER_KEY`?

2023-12-20 06:51 UTC, NishantJoshi00 commented on lib/aws/encryption.py
can you instead update the kms lambda that is written for card vault to be general purpose?

2023-12-20 09:14 UTC, dracarys18 commented on lib/aws/encryption.py
I will create an issue for this we can pick this during CDK rewrite?

2024-01-12 12:04 UTC, dracarys18 commented
All hyperswitch pods are running

<img width="1182" alt="Screenshot 2024-01-12 at 5 33 24 PM" src="https://github.com/juspay/hyperswitch-cdk/assets/43412619/90fe2fd5-a9d3-488f-977e-744b18fe9508">

CDK script successfull

<img width="1728" alt="Screenshot 2024-01-12 at 5 33 59 PM" src="https://github.com/juspay/hyperswitch-cdk/assets/43412619/41098634-a85c-425e-b446-21bdcff1b3f2">

2024-01-22 07:25 UTC, jagan-jaya requested changes

2024-01-22 07:25 UTC, jagan-jaya commented on lib/aws/eks.ts
> +        postgresql: {
use existing helm values

2024-01-22 07:25 UTC, jagan-jaya commented on lib/aws/eks.ts
>          redis: {
use existing helm values

2024-01-30 12:23 UTC, nitesh-balla commented
@dracarys18 Please resolve the conflicts. 
other than that LGTM!

2024-01-30 13:09 UTC, dracarys18 commented
Done

2024-01-30 13:24 UTC, nitesh-balla approved these changes

2024-01-30 13:24 UTC, merged