feat: free tier setup for evaluators
juspay/hyperswitch-cdk pull request #64
Opened 2024-02-02 22:45 UTC by inventvenkat

This allows evaluators of this project to deploy the whole setup of hyperswitch in their AWS account. Make sure, you are not exceeding the RDS and Elasticache's free limit which are
RDS - https://aws.amazon.com/rds/free/
Elasticache - https://aws.amazon.com/elasticache/pricing/

To use this, please bootstrap the region before running the CDK script with the following command
`cdk deploy -c aws_arn=$AWS_ARN -c free_tier=true`

2024-02-07 07:30 UTC, nitesh-balla commented
Please resolve conflicts.

2024-02-08 15:54 UTC, nitesh-balla requested changes

2024-02-09 11:06 UTC, inventvenkat commented on lib/aws/rds.ts
> +      // ],
Yes required.. Will make respective changes

2024-02-12 10:14 UTC, nitesh-balla approved these changes

2024-02-12 10:29 UTC, merged